### ISSUE TITLE
Windows 10 not launching

### ISSUE THREAD

**Issue by Guybrush101** [Sauceke/LoveMachine#120]
I cant seem to get lovemachine working. 
I install lovemachine and add our apartment. 
i run intiface - connect toy - hit disconnect
run our appartment and i run the game and nothing happens.

when i look up lovemachine in my applications its just a broken redirect. also in appdata lovemachine only shows an uninstaller. 
am i missing something?

**Comment by Sauceke** [comment]
Do you have the latest version of Our Apartment (0.3.1)?
If you do and it still doesn't work, please attach the `BepInEx\LogOutput.log` file so I can see what's going on.

**Comment by Guybrush101** [comment]
I believe its .28a. i just bought the game from their site. so it should be the latest
[LogOutput.log](https://github.com/Sauceke/LoveMachine/files/9946733/LogOutput.log)

also ty for helping

**Comment by Sauceke** [comment]
Ah crap. They didn't release 0.3 on itch.io yet, it's a patrons only build.
Well, until they do, you can use [lovemachine 2](https://github.com/Sauceke/LoveMachine/releases/tag/v2.10.0) with 0.2.8.a, but the smooth stroking feature will be missing.
Meanwhile I'll change the link to their patreon so as not to confuse people. It's cheaper to get it from there anyway.
