### ISSUE TITLE
Max Strokes (per minute) not available in 3.2.0 Koikatsu

### ISSUE THREAD

**Issue by PotatoDaze** [Sauceke/LoveMachine#121]
I was wondering if I broke something, the Max Strokes (per minute) feature does not seem to be available in 3.2.0 in my Koikatsu Party. I use Koikatsu Better Repack Release RX15 // 15.08.2022
<img width="320" alt="21117c0817fbea2c26551036cc39832e" src="https://user-images.githubusercontent.com/117675524/200381697-d9eace2c-df5c-47ad-8196-972525d67b26.png">

**Comment by Sauceke** [comment]
You can set it for each device now, by either connecting it or clicking Show Offline Devices.
Also note that from v3 on this setting won't slow down animations due to compatibility issues with other mods. It is now only used for switching between stroke zones.

**Comment by PotatoDaze** [comment]
Found it thanks! Sad that it no longer slows down animations though, that was my favorite feature! But understandable how it would conflict with some other stuff. Thanks alot for the help!

**Comment by Sauceke** [comment]
I could make a separate mod to change the timeScale, with roughly the same effect (though I'm pretty sure someone's already made one). Slowing things based on device capabilities is problematic in many ways.
Anyway, glad I could help, and if you found this project useful, please give it a ⭐.

**Comment by Sauceke** [comment]
@PotatoDaze I made a plugin that you can use to decrease animation speeds. It works in almost any game, not just Koi.
https://github.com/Sauceke/TimeScaleRandomizer/releases/tag/v1.1.0
It actually sets the speed to random, but you can choose the min and max speed freely.
