### ISSUE TITLE
Adding support for  NOR

### ISSUE THREAD

**Issue by Craxter1177** [Sauceke/LoveMachine#122]
Hey just asking if there is any way you could add support for Night of Revenge?

**Comment by Sauceke** [comment]
Looks like a 2D game to me. Are the H scenes 2D too?

**Comment by Craxter1177** [comment]
Ohhh... yeah i think so damn

**Comment by Sauceke** [comment]
You're not the first to have asked for 2D game support. 😅 At this point all I can say is, it might be a feature one day, but I'd need to do a _lot_ of research to pull it off. It's not just "3D minus 1" unfortunately. 2D drawings don't even have a body structure to begin with.
Sorry to disappoint you. If you still find this plugin useful regardless, please star it so others with similar interests can find it too.
