### ISSUE TITLE
Support for Secrossphere possible?

### ISSUE THREAD

**Issue by Unprogress** [Sauceke/LoveMachine#124]

**Comment by Sauceke** [comment]
I can't even find a working download link for this game so ¯\\_ (ツ)_/¯

**Comment by Unprogress** [comment]
Uff alright , yeah the game is a bit older :) thank you for the answer though. Not sure if I got it from good old hf back when it was alive.

**Comment by Sauceke** [comment]
If you want to upload your own copy, I'll give it a look, otherwise I'm afraid there's not much I can do.

**Comment by Unprogress** [comment]
Sure, i can do that. Since i do not know the rules of github about linksharing , would twitter be fine? :)

**Comment by Sauceke** [comment]
Yes.

**Comment by Sauceke** [comment]
Yeah, looks pretty straightforward. Can probably add it in the next release or the one after.
Thanks for the suggestion, and if you find this project useful, please give it a ⭐.

**Comment by Unprogress** [comment]
Very cool! :) Thanks for taking the time to look into it.

**Comment by Sauceke** [comment]
Secrossphere added, will be rolled out in next release.
