### ISSUE TITLE
Device Can't Connect to Plugin

### ISSUE THREAD

**Issue by Roboticman** [Sauceke/LoveMachine#126]
Hi, I'm having issues on connecting my Keon to the plugin. I've downloaded Intiface Central and did the troubleshooting by connecting my device to the server and then turning off the server and then starting up the game but still nothing. Am I doing it wrong or is there a different way? Please and Thank you.

**Comment by Sauceke** [comment]
The server must be running while the game is running.

**Comment by Roboticman** [comment]
So I'm talking to someone on the Buttplug Discord and they found a URL error.

**Comment by Sauceke** [comment]
Resolved over Discord.
