### ISSUE TITLE
LoveMachine doesn't load H scene device movements

### ISSUE THREAD

**Issue by 13cmatthews** [Sauceke/LoveMachine#127]
Intiface can connect to HNR but when loading the H scene the application fails to load device movements and displays a load of red text repeatedly.
[LogOutput.log](https://github.com/Sauceke/LoveMachine/files/10528028/LogOutput.log)

**Comment by Sauceke** [comment]
Which scene was it? Current version only supports humanoid penises (gob, human, arachne etc.)

**Comment by 13cmatthews** [comment]
The first one I noticed it on was the goblin scene near the start in the church

**Comment by Sauceke** [comment]
That's a Novel scene, I don't support those (yet).
First scene that works with the current version is the one in chapter 2 with the golem.
If it doesn't for you, let me know.

**Comment by 13cmatthews** [comment]
It works in chapter 2 thanks. hopefully you can get those novel scenes working, looking forward to it.

**Comment by Sauceke** [comment]
Yeah, will get around to it eventually.
If you found this project useful, please⭐ it. Thanks.
