### ISSUE TITLE
Does not work in VR Kanojo

### ISSUE THREAD

**Issue by patrick-krimson** [Sauceke/LoveMachine#128]
I cannot seem to get it work with VR Kanojo
The game does not seem to work with the handy or any lovense devices.
Only testing and "the orgasm" make the vibrations / strokes work

[LogOutput-vr kanojo.log](https://github.com/Sauceke/LoveMachine/files/11034985/LogOutput-vr.kanojo.log)

**Comment by Sauceke** [comment]
Confirmed, this is a bug in the latest version that affects VR Kanojo and Our Apartment.
Fix will be included in next release, meanwhile you can downgrade to 3.5.0.
Thanks for reporting this.
