### ISSUE TITLE
adding orgasm length like stroke length

### ISSUE THREAD

**Issue by kisspcdd** [Sauceke/LoveMachine#131]
It would be great to have this feature, to be able to add/modify orgasm length like the stroke length feature.

**Comment by Sauceke** [comment]
Depends whether you mean length as distance or duration.
Distance (strokers) - already configurable, just decrease shaking frequency or increase max strokes per minute (stroker moves as fast as it can during orgasm)
Duration - determined by the game itself, but I can make the minimum duration configurable (in case the in-game animation is too short).
