### ISSUE TITLE
Vibrator devices cannot stop after orgasm in H scene

### ISSUE THREAD

**Issue by lanniris** [Sauceke/LoveMachine#135]
Hi Sauceke, i really like this plugin, it works fine with my Kiiroo Keon, Thank you.
Recently i got some vibrator device (Lovense Diamo / Gush), I found that in game H scene orgasm time, the devices run at the max strength, but after orgasm end (and start a new H action), it keeps max strength and cannot stop, unless I press spacebar. And at this time, resume key won't work. The devices seems out of control and cannot sync with the game action.
I test in Koikatsu Sunshine / PlayHome / HoneySelect2, the problem is the same. I paste the koikatsu sunshine bepin log here for help. 
[LogOutput.log](https://github.com/Sauceke/LoveMachine/files/11554563/LogOutput.log)

**Comment by Sauceke** [comment]
This is indeed a bug, thank you for reporting it. Pushed a hotfix (v3.8.1) that should solve the issue.
