### ISSUE TITLE
Xibao Smart Masturbation Cup is not supported

### ISSUE THREAD

**Issue by kokono9201** [Sauceke/LoveMachine#136]
Xibao Smart Masturbation Cup is not supported
But the device can be detected and controlled by intiface

**Comment by kokono9201** [comment]
I think the reason is that it's "oscillate"

**Comment by dravpin** [comment]
Support when? i connect but every game says not supported

**Comment by Sauceke** [comment]
@dravpin This is planned in the next release since everyone and their mother is asking for it lately.

**Comment by dravpin** [comment]
> @dravpin This is planned in the next release since everyone and their mother is asking for it lately.

Oops sorry to be another everyone lmao
