### ISSUE TITLE
VR Kanojo (Steam version) problem

### ISSUE THREAD

**Issue by LikeShady** [Sauceke/LoveMachine#144]
When i start the game (i use the oculus VR option) it says: "Failed to connect to Intiface"
I've just bought the game and download the mod, i've already used with Playhome, custom maid, koikatsu and honey select and it works, no problem, it's just VR kanojo.
I'm used The handy and it connects to intiface as well as with other games so i can't understand why it doesnt work with this
![dasdas](https://github.com/Sauceke/LoveMachine/assets/33573620/522b7c33-b96b-4d1f-b0b3-6eeeeb87f0c5)

**Comment by Sauceke** [comment]
Hi, please attach your BepInEx\LogOutput.log file.

**Comment by LikeShady** [comment]
Hi, sure, here it is
[LogOutput.log](https://github.com/Sauceke/LoveMachine/files/12208054/LogOutput.log)

**Comment by Sauceke** [comment]
The client says the target machine actively refused to connect. So far I've only seen that happen when there's nothing running on localhost:12345.
Are you sure Intiface was running when you started the game? Was it running on port 12345?

**Comment by LikeShady** [comment]
Yes, I thought it could be a problem with Intiface, but when I tried to start PlayHome, it connected without any issues.
I don't know if i can help but this is the Playhome log
[LogOutput.log](https://github.com/Sauceke/LoveMachine/files/12208879/LogOutput.log)

**Comment by Sauceke** [comment]
That's an older version of LM, does it also work with the latest one?
If it doesn't, at least I'll know it's something I changed (though still have no idea what exactly).

**Comment by LikeShady** [comment]
you are right, i've updated LM and now i get the same error on Playhome too, here's the log if you need it
i think i can try to download older version to find the one working for now, thank you your time
[LogOutput.log](https://github.com/Sauceke/LoveMachine/files/12209530/LogOutput.log)

**Comment by Sauceke** [comment]
By the way, you're using Intiface Central, right?

**Comment by LikeShady** [comment]
oh, my bad, i followed an old guide for connecting the handy to other games and thought it was the same for this mod since it was working with Playhome. I was using Intiface Desktop, i tried with Central and now it work. Thanks you, i should read better next time

**Comment by Sauceke** [comment]
I still don't get why it fails _before_ the handshake though, but good to know that was the problem.
Glad I could help, and if you found this plugin useful, please give it a ⭐.
