### ISSUE TITLE
 How do I compile this project myself

### ISSUE THREAD

**Issue by YukiYukito** [Sauceke/LoveMachine#152]
I find that when I play a new animation, I usually have to wait a few seconds for lovemachine to take effect。
This phenomenon was obvious when I was playing HKR and COM3D2.
I took a look at the code of COM3d2 and wanted to try modifying it myself to see if it works.

**Comment by Sauceke** [comment]
> [How it works, limitations](https://github.com/Sauceke/LoveMachine#how-it-works-limitations)
> Whenever a new animation loop starts, LoveMachine records the relative positions of certain bones for one cycle, then it tries to guess which bones are the most likely to be involved in the action

Unity's API won't let you get keyframes from an animation at runtime, so there's no way to make this any faster.
COM3D2 and HKR both have very long animations, so the process takes longer.
If you still want to build it, install VS, Inno Setup, the required .NET versions, and the installer will run automatically after you build the solution. But it's a waste of time, you won't get better response times out of it.
