### ISSUE TITLE
Unable to Launch Game - Holy Knigt Ricca

### ISSUE THREAD

**Issue by MuncherCookie** [Sauceke/LoveMachine#157]
> I'm using the latest versions of both Love Machine (LM) and Intiface. To install LM, I used the provided installer. Whilst my toy, the Max 2, has no issue connecting to Intiface, the game crashes on startup.

Does this plugin work with both JP and EN versions of Holy Knight Ricca? The error log is attached below.
[ErrorLog.log](https://github.com/Sauceke/LoveMachine/files/13561275/ErrorLog.log)

**Comment by Sauceke** [comment]
Can't repro. Just tested starting from a clean install of the latest EN version (134) and it worked fine.
I've never seen this error before. Do you have any mods installed besides LM? Also, what are your system specs?

**Comment by MuncherCookie** [comment]
I had no additional mods apart from LM. My specs are a R9 5950x, Rtx 3090, 64GB Ddr4 3600Mhz, all running off of a Samsung m.2 SSD. I recently did a clean reinstall of windows.

The steps I take from start to finish are:
1.) Download files from DLSITE & Extract to designated location (G:\Patreon\DLSITE\HolyKnightRicca_v134en)
2.) Launch & Close Game
3.) Launch LM installer and route it to G:\Patreon\DLSITE\HolyKnightRicca_v134en\Game
4.) Game fails to launch when launcher is used, or when directly clicking on the .exe.

I'm not sure if I'm selecting the wrong location for the installer to route to, but if I just route it to the HolyKnightRicca folder, and not the Game folder, it's unable to install.

**Comment by Sauceke** [comment]
So I'm assuming it runs fine without bepinex.
Are you on win 10 or 11?

**Comment by MuncherCookie** [comment]
If I delete the bepinex folder after installation of LM, the game launches.

I'm on windows 10.

**Comment by Sauceke** [comment]
No idea what causes this, but it seems to happen right at the entry point of BepInEx.
Does it also crash if you install the mod then remove the "BepInEx\plugins\HKR_LoveMachine" folder?

**Comment by MuncherCookie** [comment]
I just deleted the "HKR_LoveMachine" folder, and it fails to launch. The terminal window pops up for a brief moment, then it crashes. Is there any possibility there is an issue with the way I install/extract the game files, or my version of the game?

**Comment by Sauceke** [comment]
No, this sounds like a bug in either BepInEx or Doorstop.
BepInEx 6 is still a work in progress, so there's no guarantee it will work in every environment.
Someone else has already opened an issue with the exact same stack trace in the BepInEx repo: https://github.com/BepInEx/BepInEx/issues/634
You could leave a comment there to indicate you're having the same issue. I'm afraid there isn't much more we can do about this.

**Comment by MuncherCookie** [comment]
Alright, that's quite annoying. I'll wait for updates I guess.

Below is a short recording of the installation of LM, just in case you would like to see if I'm installing it correctly. If I don't make any discrepancies in the video, I'll wait for further updates to BepInEx 6.

https://github.com/Sauceke/LoveMachine/assets/85422782/dbfb1561-4a5d-4b42-a98a-080513e9e0d8

**Comment by Sauceke** [comment]
Nope, that's the way to install it.
You could also try running it with the latest nightly build of bepinex, which is a bit more recent than what is included in LM.
https://builds.bepinex.dev/projects/bepinex_be/679/BepInEx-Unity.IL2CPP-win-x64-6.0.0-be.679%2B49775dc.zip
Delete the BepInEx folder, then extract the ZIP into HolyKnightRicca_v134en\Game, then run the installer again. There's a near-zero chance it will solve the problem, but it's your last hope (save for trying on a different machine).

**Comment by MuncherCookie** [comment]
Even without me running the installer for LM, after extracting the above .zip, the game fails to launch. I'll wait for Bepinex updates I guess.
