### ISSUE TITLE
What to do when downloading for the game "Our Apartment"?

### ISSUE THREAD

**Issue by livourus** [Sauceke/LoveMachine#159]
> Are you using the latest version of LoveMachine and Intiface Central?
(If not, update and try again. Your problem might already be solved in the latest version.)

yes

> Did you install LoveMachine using the installer? If not, how did you install it?

yes

> Can you connect your device to Intiface Central?
(Intiface is not my project. If you have trouble using it, please read the Help tab of Intiface, and if the problem persists, raise an issue here: https://github.com/intiface/intiface-central/issues/new)

yes

> Describe the problem. Make sure to attach your BepinEx\LogOutput.log file (or in some games, the output_log.txt file in the game directory).

I read that Bepin plugins wont work with ILC2PP but theres no prexisting bepin folder to delete so what do I do to connect love machine?

**Comment by Sauceke** [comment]
The latest supported version of OA is 0.3.1.
