### ISSUE TITLE
Extract Animation Phase timings to external file

### ISSUE THREAD

**Issue by erodozer** [Sauceke/LoveMachine#16]
Currently Animation phases for strokers are hard coded in the ButtplugController.cs file.  Extracting this into an external file such as an XML or JSON to be included with the plugin would allow for tweaking without having to compile, as well as lower the barrier for entry of having people contribute and test timings.  This can be particularly helpful for expanding the list of supported animations to include ones that are added by extensions such as KPlug.

**Comment by Sauceke** [comment]
Agreed, though these values are not expected to change unless they were incorrectly measured in the first place.
But there are a lot of mods that add custom poses, and syncing all of them would be a massive pain. Letting the player tweak them is better than nothing.
