### ISSUE TITLE
Sexaroid girl not sending anything to intiface when animation plays for example it connects just fine.

### ISSUE THREAD

**Issue by ghost** [Sauceke/LoveMachine#160]
> Are you using the latest version of LoveMachine and Intiface Central?
(If not, update and try again. Your problem might already be solved in the latest version.)

Tried latest then tried to downgrade to the version with last sg update.

> Did you install LoveMachine using the installer? If not, how did you install it?

Installed trough installer.

> Can you connect your device to Intiface Central?
(Intiface is not my project. If you have trouble using it, please read the Help tab of Intiface, and if the problem persists, raise an issue here: https://github.com/intiface/intiface-central/issues/new)

Yeas

> Describe the problem. Make sure to attach your BepinEx\LogOutput.log file (or in some games, the output_log.txt file in the game directory).

It connects with out issues to intiface, but it does not seem to send anything to it when animations for example play at all.

[LogOutput.log](https://github.com/Sauceke/LoveMachine/files/14251071/LogOutput.log)

**Comment by Sauceke** [comment]
My guess is that you didn't enable auto piston. IIRC you need to grab the pp and press up on the thumbstick or something similar to enable it.

**Comment by ghost** [comment]
I tried with her serving ill give that a try next time I have time and report back I guess.

**Comment by ghost** [comment]
[LogOutput.log](https://github.com/Sauceke/LoveMachine/files/14251626/LogOutput.log)

New log, yea auto does nothing here wont just work on this game.

**Comment by Sauceke** [comment]
Can you check again with debug logging enabled in BepInEx.cfg?
Also, what modding framework does the AutoTranslator come from? Other frameworks can interfere with bepinex in a lot of ugly ways.

**Comment by ghost** [comment]
Well it most likely due to xunity.autotranslator having bebini plugin avaible and I have setup it trough reipatcher, so thats most likely the culprit will close this for now, because I asume thats the reason.
