### ISSUE TITLE
no device movement in honeyselect1

### ISSUE THREAD

**Issue by noyjitat** [Sauceke/LoveMachine#165]
> Are you using the latest version of LoveMachine and Intiface Central?
(If not, update and try again. Your problem might already be solved in the latest version.)

Yes

> Did you install LoveMachine using the installer? If not, how did you install it?

Installer

> Can you connect your device to Intiface Central?
(Intiface is not my project. If you have trouble using it, please read the Help tab of Intiface, and if the problem persists, raise an issue here: https://github.com/intiface/intiface-central/issues/new)

Yes

> Describe the problem. Make sure to attach your BepinEx\LogOutput.log file (or in some games, the output_log.txt file in the game directory).

So apparently at some point this project was made to work with honeyselect 1 now but it isn't working on my own end yet it works just fine with the other games: (hs2, playhome, koikatsu sunshine). Since I have some cards that were never updated by the creators to hs2 I still need to use hs1.  

If you could point me to exactly what Im missing or need to configure it would be greatly appreciated. Also I can't figure out where you go to configure the plugin much like in hs2. In hs2 you simply press f1 and find lovemachine in the list of plugins but I can't find anything similar in hs1. Please note I am just trying to use this in the normal gameplay mode not in VR.
[LogOutput.log](https://github.com/Sauceke/LoveMachine/files/14440633/LogOutput.log)

**Comment by Sauceke** [comment]
Can't guarantee compatibility with repacks. There could be another mod or modding framework in there interfering, or even a modified game assembly.
Logs don't even show the plugin starting up, so I have nothing to debug.

**Comment by noyjitat** [comment]
is there a repack you have used and tested? I figured everyone used repacks LOL. It works flawlessly with all the other games mentioned which are also repacks.

**Comment by Sauceke** [comment]
I tested with the official version.
Your repack seems to have IPA mods, so that's not gonna work together with BepInEx unless you use the IPA loader (https://github.com/BepInEx/IPALoaderX). Don't ask me how that works though, never tried it.
