### ISSUE TITLE
com3d2 working in yotogi, not in h events

### ISSUE THREAD

**Issue by yuria24** [Sauceke/LoveMachine#166]
> Are you using the latest version of LoveMachine and Intiface Central?
(If not, update and try again. Your problem might already be solved in the latest version.)

Yes

> Did you install LoveMachine using the installer? If not, how did you install it?

Yes

> Can you connect your device to Intiface Central?
(Intiface is not my project. If you have trouble using it, please read the Help tab of Intiface, and if the problem persists, raise an issue here: https://github.com/intiface/intiface-central/issues/new)

Yes

> Describe the problem. Make sure to attach your BepinEx\LogOutput.log file (or in some games, the output_log.txt file in the game directory).

Does lovemachine work for H-events in com3d2? they consist of looping animations like yotogi, is it possible to make it work for them? Thank you so much

**Comment by Sauceke** [comment]
Haven't really played the game so I don't know what H-events are or how to trigger one.
If there's an easy way to do it then let me know how, and I'll see if I can add them.

**Comment by yuria24** [comment]
No worries! Thank you for the consideration, it is similar to yotogi, but there is a storyline like a visual novel and it just loops animations, they should be in your recollection mode -> h - events. To unlock them, you must play the game and through the events menu, but you can use this exe Maid Fiddler to unlock all of them if I recall correctly and view it in recollection mode. 

https://github.com/ghorsington/COM3D2.MaidFiddler

Should be easy to implement, not sure though, but thank you for replying!

**Comment by yuria24** [comment]
I will attach some pictures soon

**Comment by yuria24** [comment]
![image](https://github.com/Sauceke/LoveMachine/assets/161983865/d786e22c-6d64-44ed-a380-f5158ec7a2b0)
Just launch Maid Fiddler after your save loads, check all of those, and then go in recollection mode -> h events, should be a lot there.

**Comment by noduyan** [comment]
Hi, I also hope this issue is solved.  I don't know much about this so I apologize if I'm wrong.

Looking at Com3d2Game.cs, it looks like LoveMachine is started and ended in YotogiPlayManager state. Therefore I don't think it will work in anything other than Yotogi.
It would be nice if it could work in H event scenes too, but would it be difficult to add a function to force start it with a shortcut key or something regardless of the scene?

**Comment by Sauceke** [comment]
Done. Next release will have H event support.
If you found this project useful, please give it a ⭐.

**Comment by Sauceke** [comment]
Released.
