### ISSUE TITLE
Kiiroo Keon

### ISSUE THREAD

**Issue by dravpin** [Sauceke/LoveMachine#167]
> Are you using the latest version of LoveMachine and Intiface Central?
(If not, update and try again. Your problem might already be solved in the latest version.)

[Release v3.17.0 | intiface 2.5.7]

> Did you install LoveMachine using the installer? If not, how did you install it?

[Yes]

> Can you connect your device to Intiface Central?
(Intiface is not my project. If you have trouble using it, please read the Help tab of Intiface, and if the problem persists, raise an issue here: https://github.com/intiface/intiface-central/issues/new)

[Yes]

> Describe the problem. Make sure to attach your BepinEx\LogOutput.log file (or in some games, the output_log.txt file in the game directory).

[LogOutput.log](https://github.com/Sauceke/LoveMachine/files/15056659/LogOutput.log)

during faster h scenes in koikatsu sunshine the keon seems to just pause momentarily. While at slower speeds it works just fine and syncs pretty much 1 to 1 i tried the default settings i tried setting the strokes per minute as per what keon says i tried most of the settings but cant seem to fix it

**Comment by Sauceke** [comment]
Most likely reasons:
- slow bluetooth adapter (should be at least 5.0 with EDR)
- bad reception due to obstacles or distance from pc
- your setup is fine and the Keon just can't keep up

If you tell me the exact position name and the speed level as percentage I can check if my Keon can handle it.

**Comment by dravpin** [comment]
> Most likely reasons:
> 
> * slow bluetooth adapter (should be at least 5.0 with EDR)
> * bad reception due to obstacles or distance from pc
> * your setup is fine and the Keon just can't keep up
> 
> If you tell me the exact position name and the speed level as percentage I can check if my Keon can handle it.

just free h cowgirl pose auto on the fastest although the weird behaviour starts happen about halfway

**Comment by Sauceke** [comment]
Tried with my Keon and it was able to keep up fine. There were minor variations in the rhythm but it didn't miss a single stroke.

If yours does, I suspect it's because of one of the first 2 reasons I mentioned earlier.

**Comment by dravpin** [comment]
Ok so its been a while but ive got an update for bluetooth i was using the ASUS-BT500 ive switched to the TP-Link ub500 to see if that makes any difference but idk they're both bluetooth 5.0 as for EDR they both have support for it there is no obstacles in the way and the distance is probably as close as i can get to my pc


https://www.asus.com/ca-en/networking-iot-servers/adapters/all-series/usb-bt500/ 
https://www.tp-link.com/ca/home-networking/adapter/ub500/

**Comment by dravpin** [comment]
Just tested didnt make difference it still hitchs a bunch even without the sleeve so i dont know anymore i deleted intiface the lovemachine mod and its config downloaded the latest of both updated my game opened intiface connected the kirro openned the game clicked test in plugin settings and just did the free h cowgirl pose auto on the fastest and it still hitchs

Are there settings im supposed to set for the kirro? if so what are they?

**Comment by Sauceke** [comment]
If you have an internal bluetooth adapter you might want to disable it in the BIOS to make sure it uses the usb one.
And make sure smooth stroking is disabled in plugin settings (though if it isn't, you should have problems at slow speeds too).

**Comment by dravpin** [comment]
> If you have an internal bluetooth adapter you might want to disable it in the BIOS to make sure it uses the usb one. And make sure smooth stroking is disabled in plugin settings (though if it isn't, you should have problems at slow speeds too).

I do not have an internal Bluetooth adapter and smooth stroking is off what are your other settings?

**Comment by dravpin** [comment]
Sorry didn't mean to do that mobiles kinda buggy

**Comment by Sauceke** [comment]
The default plugin settings should be fine.

How much of a lag are we talking about? Is it going completely the opposite way? Or is it the right direction but uneven timing?

**Comment by dravpin** [comment]
it just pauses for a second sometimes why i said hitchs it does it quite a bit no idea

**Comment by Sauceke** [comment]
Yeah, pausing for a whole second is definitely not normal. For 1/10th of a second would be normal.
Does it also lag when you use it with the Kiiroo Connect app?

**Comment by dravpin** [comment]
> Yeah, pausing for a whole second is definitely not normal. For 1/10th of a second would be normal. Does it also lag when you use it with the Kiiroo Connect app?

no

**Comment by Sauceke** [comment]
Weird. Then maybe try installing Intiface on your phone and controlling it from there? IIRC you just need to open the lovemachine settings and change the IP address in Intiface Settings > WebSocket Host setting to your phone's IP address and it should work.

**Comment by dravpin** [comment]
> Weird. Then maybe try installing Intiface on your phone and controlling it from there? IIRC you just need to open the lovemachine settings and change the IP address in Intiface Settings > WebSocket Host setting to your phone's IP address and it should work.

i gave the mobile app on my s24 ultra a shot and nope some problem its so weird at full speed in intiface it doesnt hitch in game it does ocs go brrr which is for vrchat also does this so it isnt a love machine problem

**Comment by Sauceke** [comment]
Closing because I don't think I can give you meaningful help on this.
If it's Intiface related then someone on the [Buttplug](http://discord.buttplug.io/) or [Kiiroo](https://discord.com/invite/w9tqXSwekb) discord might know what's going on.
