### ISSUE TITLE
Game no reading the connection, im not sure what i did wrong

### ISSUE THREAD

**Issue by ramar9531** [Sauceke/LoveMachine#168]
> Are you using the latest version of LoveMachine and Intiface Central?
(If not, update and try again. Your problem might already be solved in the latest version.)

LoveMachine V 3.17.0, Intiface Central 2.5.7 + 25

> Did you install LoveMachine using the installer? If not, how did you install it?

I installed via the installer

> Can you connect your device to Intiface Central?
(Intiface is not my project. If you have trouble using it, please read the Help tab of Intiface, and if the problem persists, raise an issue here: https://github.com/intiface/intiface-central/issues/new)

My device connects to intiface central 

> Describe the problem. Make sure to attach your BepinEx\LogOutput.log file (or in some games, the output_log.txt file in the game directory).

Only game i have currently is Our Apartment and to be honest im not sure what i am doing wrong but i seems as though game isnt picking up on the intiface central connection not sure if i installed incorrectly have my setting done incorrectly but i have fresh installed everything at least twice and i am stumped

**Comment by Sauceke** [comment]
Which version of OA? Current supported version is 0.3.1. Haven't caught up with the latest updates, though I eventually intend to.

**Comment by ramar9531** [comment]
gotcha thats more the likely the issue ill download the earlier issue and give it a shot i was using Version 0.5.2.d.

**Comment by Sauceke** [comment]
Assuming it works now, if not please reopen.
