### ISSUE TITLE
Suggestion: use velocity * depth for vibration strength, instead of just velocity

### ISSUE THREAD

**Issue by programotter** [Sauceke/LoveMachine#17]
This gives a feeling of rhythm to vibration output, rather than just going brrrrrrrr all the time :)

I suggest velocity should be a range [0, 1], so that at no penetration it gives an output strength of 0, and at maximum depth it gives the same vibration strength as before.

**Comment by Sauceke** [comment]
For the record this was [the first use case of Buttplug+KK they talked about](https://discord.com/channels/447114928785063977/476358846764548137/715155243830345778) on discord.

I've never used one of them vibrating thingies, so I can't judge if this is any better than a flat line. But it sounds interesting. I'm happy with this as long as the constant output version stays selectable in the config.

**Comment by erodozer** [comment]
I'll be happy to take this one
