### ISSUE TITLE
Device doesn't react from Koikatsu

### ISSUE THREAD

**Issue by pluto13x** [Sauceke/LoveMachine#170]
> Are you using the latest version of LoveMachine and Intiface Central?
(If not, update and try again. Your problem might already be solved in the latest version.)

yes

> Did you install LoveMachine using the installer? If not, how did you install it?

yes

> Can you connect your device to Intiface Central?
(Intiface is not my project. If you have trouble using it, please read the Help tab of Intiface, and if the problem persists, raise an issue here: https://github.com/intiface/intiface-central/issues/new)

yes

> Describe the problem. Make sure to attach your BepinEx\LogOutput.log file (or in some games, the output_log.txt file in the game directory).
[LogOutput.log](https://github.com/user-attachments/files/15526607/LogOutput.log)

the device connects to Intiface, and Intiface connects to Koikatsu. When clicking "test" in the LoveMachine settings for my device in Koikatsu, nothing happens. The device does react from HoneySelect 2

**Comment by Sauceke** [comment]
Can confirm this is a bug, thanks for the heads up.
This issue only affects the test button, and only outside of H scenes. I'll fix it shortly but in the meantime you should still be able to use the plugin with a vibrator like normal.

**Comment by pluto13x** [comment]
hey, it actually doesn't react from anywhere in the game

**Comment by Sauceke** [comment]
The test button or vibration in general?
Can I see the logs?

**Comment by Sauceke** [comment]
Fixed the bug with the test button, fix will be in the next release.
If vibrators still don't work anywhere for you, please open a separate issue.
