### ISSUE TITLE
VR Kanojo（Steam版）問題2

### ISSUE THREAD

**Issue by tonylio88** [Sauceke/LoveMachine#171]
> Are you using the latest version of LoveMachine and Intiface Central?
(If not, update and try again. Your problem might already be solved in the latest version.)

YES

> Did you install LoveMachine using the installer? If not, how did you install it?

YES

> Can you connect your device to Intiface Central?
(Intiface is not my project. If you have trouble using it, please read the Help tab of Intiface, and if the problem persists, raise an issue here: https://github.com/intiface/intiface-central/issues/new)

YES

> Describe the problem. Make sure to attach your BepinEx\LogOutput.log file (or in some games, the output_log.txt file in the game directory).

When I press the green start button, after a few seconds it turns back to the green start button and no output_log.txt is output.

**Comment by Sauceke** [comment]
For the Steam version you might want to install [the HF patch for VRK](https://github.com/ManlyMarco/VRK-HF_Patch/releases/tag/v1.1). You can also install lovemachine from there, no need to use the lovemachine installer.

**Comment by tonylio88** [comment]
Thanks a lot!

**Comment by Sauceke** [comment]
Sure thing, and if you found this project useful, please give it a ⭐.
