### ISSUE TITLE
Question: Solace is a stroker with depth and speed, why is it only listed as an oscillator?

### ISSUE THREAD

**Issue by TheEternalDarkness** [Sauceke/LoveMachine#176]
The Lovense Solace is a stroker with depth and speed controls. Why is it treated only as an oscillator?

**Comment by Sauceke** [comment]
I wanted to prevent people from buying something with false expectations.
Edited the README to further clarify this:

>⚠ The devices listed under Oscillators have no positional feedback. They don't know which way is up and down, so they can't accurately sync to in-game characters. If you want to buy a device that can, you're looking for something under Strokers.

Would be more accurate to call strokers "devices with positional output", but no one would understand what that means, and I have to call them *something*.
