### ISSUE TITLE
Other Illusion Games Compatible?

### ISSUE THREAD

**Issue by Syunica** [Sauceke/LoveMachine#19]
Can i use this with HS1/HS2 aswell? Just curious because there is no other plugin for HS2.. #

**Comment by Sauceke** [comment]
No, for hs2 it has to be written from scratch. I might give it a try when I have really much time to waste and/or feel extremely masochistic. Well, at least the interfacing part would be easier as hs2 is .net4.6, so it's compatible with the buttplug FFI for C#. Much easier than the websocket stuff we're doing in this .net3.5 fossil of a game. You could even start a buttplug server from HS2 no problem. As for the gameplay integration... knowing Illusion's code quality standards I reckon it won't be easy.

**Comment by Sauceke** [comment]
Closing in absence of action items.

**Comment by Sauceke** [comment]
Reopening because I feel extremely masochistic.
