### ISSUE TITLE
Possible to support OSR2+ and OSR6?

### ISSUE THREAD

**Issue by laueno2** [Sauceke/LoveMachine#52]
Hi, just curious if there is plan in the future to support OSR2+ and OSR6 (6DoF)?
https://www.patreon.com/tempestvr/posts

Thank you very much creating this!

**Comment by Sauceke** [comment]
Hi, this mod doesn't interface with devices. Please ask either the developer of the device or the developers of [Buttplug](https://github.com/buttplugio/buttplug) to add Buttplug protocol support for the device.
