### ISSUE TITLE
Lovense Max 2 : Support air pump

### ISSUE THREAD

**Issue by RepairUnit3k6** [Sauceke/LoveMachine#57]
Lovense max 2 have air pump that makes toy more tight or loose on the fly. I was wondering if is possible to add this support, make it tighter the deeper are....._characters inside each other_...Theoretically you could reuse information used for strokers, just instead of stroking it would get tighter

**Comment by Sauceke** [comment]
Depends on buttplugio/buttplug#337
Possible workaround: raw device messages.
@nhydock, you already have this device. If you're interested in adding this, I won't hold you back. Otherwise I'll mark it as blocked.

**Comment by erodozer** [comment]
I've never been able to see the air pump in a max work nearly as responsively as a stroker, at least based on lovense's apps.  It takes time to pump, and even then it's used for simulating contractions and general pressure with a level setting that's more like vibrator intensity than a stroker position.  

I don't think you'd get that good of an experience tying it to animation position as opposed to making it tighter/looser based on gameplay elements, such as female excitement gauge in koikatsu.

**Comment by Sauceke** [comment]
> I don't think you'd get that good of an experience tying it to animation position as opposed to making it tighter/looser based on gameplay elements, such as female excitement gauge in koikatsu.

@RepairUnit3k6, @nhydock would either of you want a feature like that?
Looked at the Lovense API. Seems the syntax is just "Air:Level:x;" where x is between 0 and 5 (exclusive?)
Sending that as a payload to RawWriteCmd should work.
https://lovesense-py.readthedocs.io/en/latest/protocol.html

**Comment by RepairUnit3k6** [comment]
Nhydock is right in fact it isnt as quick but having some way game affect it would be neat....Lemme think. Considering it isnt as responsive it propably would be better to get tighter and tighter with excitement level, with reset to 0 at climax. That should work better since excitement does not rises as fast so it should have plenty of time to pump

**Comment by RepairUnit3k6** [comment]
Aftertought. Set it to max at climax and then loosen up over time . That would propably reflect better to how girls rect in game where they climax and then longer pause they rest a bit

**Comment by Sauceke** [comment]
Just upgraded to message spec v3, which supports this out of the box.
Except now half of the games in lovemachine don't have excitement levels, so a fallback/replacement would be nice. Preferably something that always works.
Speed comes to mind, but that's tricky since it's not a bounded interval, so we'd have to transform it somehow.
Or it could just be a constant pattern, like a sine wave or something.
Any thoughts?

**Comment by Sauceke** [comment]
Added time-based and stroke length-based constriction control. Closing as done.
If you found this project helpful, please give it a ⭐.
