### ISSUE TITLE
Is OSR2 supported?

### ISSUE THREAD

**Issue by BugMonkey42335** [Sauceke/LoveMachine#66]
I'm uncertain if I'm doing something wrong or if Intiface Desktop isn't detecting things.

**Comment by Sauceke** [comment]
OSR2 is supported in Intiface but is [known to have bugs](https://discord.com/channels/353303527587708932/453328145857118220/896325396889477131).
I can't help you with that as I'm not a maintainer of Intiface. Try asking around on the Buttplug discord.
