### ISSUE TITLE
Koikatsu Darkness

### ISSUE THREAD

**Issue by Velasa** [Sauceke/LoveMachine#70]
Oddly I can't get Darkness to function with this setup, I've tried adjusting settings with no luck. Sadly I've tried to research the issue but Google isn't turning anything up.

**Comment by Sauceke** [comment]
Hi, please attach your output_log.txt after doing a gameplay that reproduces the issue.

**Comment by Velasa** [comment]
[output_log.txt](https://github.com/Sauceke/BepInEx.LoveMachine/files/7508858/output_log.txt)
Howdy, really sorry for the delay. I don't get a lot of freetime these days. Attached as requested.

**Comment by Sauceke** [comment]
Sorry for the inconvenience but could you repeat it with [this modified version](https://github.com/Sauceke/BepInEx.LoveMachine/suites/4318554715/artifacts/112940140)?
I added some extra logging because nothing out of the ordinary was indicated in your logs.

**Comment by Sauceke** [comment]
Forgot to mention, please also set both UnityLogListening and WriteUnityLog to Enabled. You can find these settings in Plugin Settings > BepInEx.

**Comment by Velasa** [comment]
[output_log.txt](https://github.com/Sauceke/BepInEx.LoveMachine/files/7517497/output_log.txt)
I put the modified files in and ran it again.

**Comment by Sauceke** [comment]
This is now fixed, and the fix will be included in the next release.
