### ISSUE TITLE
Is there support for these games?

### ISSUE THREAD

**Issue by EEstyle-eu** [Sauceke/LoveMachine#71]
Koikatsu Sunshine (can't test VR patch as it's not released yet)   ------ something has changed ?
Koikatsu  Party (illusion) -----is there any support?
PlayHome (illusion)  ----- is there any support?

thx.

**Comment by Sauceke** [comment]
Koikatsu Sunshine: the plugin works in VR, forgot to update readme
Koikatsu Party: yes, the Koikatsu version also works in Koikatsu Party
PlayHome: no support at the moment

**Comment by Sauceke** [comment]
@EEstyle-eu and now it also supports PlayHome
it was ez
