### ISSUE TITLE
How to set it up to After Service Gangbang Addicts

### ISSUE THREAD

**Issue by EEstyle-eu** [Sauceke/LoveMachine#83]
How to set it up to After Service Gangbang Addicts ?
Where to install. Which folder?
And which file- LoveMachine_for_Houkago_Rinkan_Chuudoku.zip ? This

thx

**Comment by Sauceke** [comment]
Updated installation instructions, please read here: https://github.com/Sauceke/BepInEx.LoveMachine/tree/mastur/doc#installation
