### ISSUE TITLE
LoveMachine does not work

### ISSUE THREAD

**Issue by superultraex** [Sauceke/LoveMachine#84]
hi
I have made settings referring to the instructions, but it doesn't work.
The log shows several warnings.
Is there anything I should review in the settings?

thanks.

[LogOutput.log](https://github.com/Sauceke/BepInEx.LoveMachine/files/7798939/LogOutput.log)

**Comment by Sauceke** [comment]
New version of Intiface has a bug where it sometimes fails to scan devices.
Go to Intiface > Devices > Connect to server and scan
Wait until your device appears on the list, then click Disconnect from server.
If it doesn't appear, restart the server and repeat the previous step.
Then start up the game and try again.

**Comment by Sauceke** [comment]
Does this resolve your issue?

**Comment by superultraex** [comment]
Thank you so much for reply.

Yes. This step worked fine for me.
