### ISSUE TITLE
Request: Honey Select 2 Studio NEO Support

### ISSUE THREAD

**Issue by ShinySolo** [Sauceke/LoveMachine#85]
As per title, is it possible to add Studio NEO support to LoveMachine? 

Many people use NEO to create custom scenes, it would be awesome if support was added.

**Comment by Sauceke** [comment]
It should be possible.

**Comment by ShinySolo** [comment]
If you could find the time to include this support, it would be great. If not, then thank you anyway for Love Machine!

**Comment by Sauceke** [comment]
Done. Next release will support Timeline animations in Studio.
If you found this project helpful, please give it a ⭐. Thank you.
