### ISSUE TITLE
Support for insult order and the new game of miconisomi

### ISSUE THREAD

**Issue by RPKU** [Sauceke/LoveMachine#86]
Does it possible to support insult order of miconisomi and the new game they haven't released?

**Comment by Sauceke** [comment]
Planning to do it eventually.

**Comment by Sauceke** [comment]
I haven't done it yet :)

**Comment by Sauceke** [comment]
Insult Order added, moved Summer In Heat request to #88.
Closing this issue.

**Comment by RPKU** [comment]
Great! Waiting for the release!
