### ISSUE TITLE
About the matter that the cooperation with Calor does not go well

### ISSUE THREAD

**Issue by youzoom64** [Sauceke/LoveMachine#91]
It doesn't work
I'll put output_log.txt here
I would be grateful if you could tell me what is wrong.

[output_log.txt](https://github.com/Sauceke/LoveMachine/files/8523880/output_log.txt)

**Comment by Sauceke** [comment]
Hi,
A number of things I'm interested in:
- What is the name of your device in your Bluetooth settings? Does it start with "LVS"?
- Did you turn it on before starting the game?
- Did it, at any point, stop blinking red?

**Comment by youzoom64** [comment]
I'm sorry, I reviewed my behavior from your question and it succeeded !
Thank you for your efforts, it's okay !

**Comment by Sauceke** [comment]
Glad I could help and sorry about the severe lag. Let's hope a new firmware version will make it better.
