### ISSUE TITLE
[COM3D2] Emergency stop is not guaranteed to work in VR mode

### ISSUE THREAD

**Issue by ghost** [Sauceke/LoveMachine#95]
I don't recall this being an issue in the VR modes of the Illusion games (I'll double check that to make sure later). But yeah, I got the crap instead of coom beaten out of me by my device. Luckily, pulling the power plug always works.

From what I've tested so far (not that much), in order for any keyboard input including the emergency stop (and restart) button to work, you need to use your VR controllers to drag that small ui menu to a place in front of you such that it is visible on your monitor. Then, you need to make sure you position the mouse such that it is not hovering over any ui buttons whilst being visible on the monitor, which will finally allow you to use keyboard input.
Since it's a keyboard and mouse issue, I don't have high hopes for a solution in the same realm. If I feel like it, I can explore some UI-based alternatives, if you don't consider it out of scope or not worth pursuing for the mod.

**Comment by Sauceke** [comment]
Was your bepinex console on? I noticed it steals focus from the game when it's on so you're typing into the console instead of the game.
I didn't see any correlation between where the tablet is and whether the kill switch works.

**Comment by ghost** [comment]
Possibly. I'll check to make sure sometime in the next few days to see if that's the case.

**Comment by ghost** [comment]
~I disabled the console window but unfortunately the problem persists. It feels like the game is always losing focus in VR mode. I find that I need to click the mouse or press a button on the controller in order to get the emergency stop and start buttons to work for a window of a couple of seconds, after which the buttons don't work again.
Is that happening for you? If not, then it may be because of the mods that I have installed.~

Right after posting this, things started working as expected, in the same game instance. I'm not sure what's going on. I'll do another test sometime later to see if the issue appears again. Nothing of note appeared in the logs. Other than that, I think disabling the console did the trick. It'd be good if this was put on the readme.

**Comment by ghost** [comment]
Disabling console was the solution. Thanks.
