### ISSUE TITLE
Low frame rates cause sporadic stroker movement

### ISSUE THREAD

**Issue by ghost** [Sauceke/LoveMachine#96]
Low frame rates (below ~30, around ~20~ 10) where the animation is visibly skipping causes the stroker to move dangerously fast. Combining this with the performance hit and current lack of reliable emergency stop button in VR can cause some unpleasant surprises.

Again, I don't recall this being an issue in the Illusion games.

**Comment by Sauceke** [comment]
I need some clarification on this. Are you saying the plugin is directly causing noticeable FPS drop in COM3D2? Or are you saying that when the FPS drops for unrelated reasons, the stroker starts misbehaving? If it's the first one, that calls for a ticket in its own right.

**Comment by ghost** [comment]
I believe it's the second case, e.g. if you have a lower end graphics card, etc. The performance hit I was referring to was just the general comparison between the VR and desktop performance of the game itself. I wasn't clear about that.

**Comment by Sauceke** [comment]
I doubt this is specific to COM3D2 as we don't have anything in place that checks for dropped frames yet.

**Comment by ghost** [comment]
I'll test for this in the other games using my GT 710 (and/or by somehow limiting frame rate) and we'll see.

**Comment by Sauceke** [comment]
No need, instead please post a log file from com3d2 when this happens, and the name of the animation where it happened. That's probably enough to find the exact cause.

**Comment by ghost** [comment]
I remember it being the binaural handjob, binaural seated cowgirl and some other non-binaural one. It hasn't happened since the opening of this issue, so I can't blame it on the animations themselves. But yeah, I'll do that.
