### ISSUE TITLE
Adding support for OSR2/SR6 T-Codes

### ISSUE THREAD

**Issue by CrispyBearcon** [Sauceke/LoveMachine#98]
Hi,

sorry if its not allowed to use the issue feature for a feature request. If not wanted please delete or close.

I wanted to ask if its possible to add support for t-codes for OSR2/SR6 so it can do more than just "stroking" over intiface like it can do in Virt-A-Mate?

Thanks!

**Comment by Sauceke** [comment]
Syncing in LM is based on distances, not coordinates. Also, AFAIK Buttplug doesn't support multi-axis movement yet. So it's way too early to even think about this. I'd say, ask me again in a year.

**Comment by CrispyBearcon** [comment]
Hi,

thanks for the fast reply. i thought of direct sending commands over serial to osr2/sr6 and skip buttplug. But i guess that would mean a loooot of work.
